name: Audit & Install Casks

on:
  push:
    branches:
      - main
    paths:
    - '.github/workflows/audit-cask.yml'
    - 'Casks/**'
  workflow_dispatch:

jobs:
  audit:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: Cache Homebrew downloads
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/Library/Caches/Homebrew
        key: homebrew-${{ runner.os }}-${{ hashFiles('Casks/**') }}
        restore-keys: |
          homebrew-${{ runner.os }}-

    - name: Update Homebrew
      run: brew update --auto-update

    - name: Enable Rosetta 2
      run: softwareupdate --install-rosetta --agree-to-license

    - name: Install Go
      run: |
        brew uninstall --force go@1.21
        brew cleanup -s go@1.21
        brew cleanup --prune-prefix
        brew install --force go

    - name: Tap Repository
      run: brew tap idleberg/asahi

    - name: Audit Casks
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
      run: |
        for file in ./Casks/*.rb
        do
          if [ "$(basename "$file")" = "io.rb" ]; then
            echo "Skipping audit for $file"
            continue
          fi
          echo "Auditing cask $file"
          brew audit idleberg/asahi/$(basename ${file%.rb}) --cask --online
        done

    - name: Install Casks
      run: |
        for file in ./Casks/*.rb
        do
          echo "Installing cask $file"
          brew install idleberg/asahi/$(basename ${file%.rb}) --cask
        done

    # - name: Test Casks
    #   run: |
    #     for file in ./Casks/*.rb
    #     do
    #       echo "Testing cask $file"
    #       brew test $(basename ${file%.rb})
    #     done

    - name: Cleanup
      run: brew cleanup --prune=all
